jobs:
  build:
    executor:
      name: go/default
      tag: "1.15"
    steps:
      - checkout
      - go/load-cache
      - go/mod-download
      - go/save-cache
      - make test
orbs:
  go: circleci/go@1.3.1
version: 2.1
workflows:
  main:
    jobs:
      - build
